---
#depends_on:
#  - pull

matrix:
  BASE:
    - apache
  SUB:
    - full
    - cron
    - smb

when:
  - branch: main
    event: [push]


variables:
  - &file Dockerfile
  - &dhub https://index.docker.io/v1/
  - &arch linux/amd64
  - &repo bksolutions/nextcloud

steps:
  prepare:
    image: alpine:latest
    commands:
      - cp -avrf nextcloud/.examples/dockerfiles/${SUB}/${BASE}/. .
    #  - sed -i -e "s|nextcloud:${BASE}|forgejo.home309.duckdns.org/containerimages/nextcloud:${BASE}"
    #  - cat Dockerfile
  buildx:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: *arch
      dry_run: false
      repo: *repo
      tags: 
        - ${BASE}-${SUB}
      build_args:
        - VERSION="${BASE}-${SUB}"
        - CREATED="${CI_PIPELINE_STARTED}"
        - REVISION="${CI_COMMIT_SHA}"
      #label:
      #  org.opencontainers.image.revision="${CI_COMMIT_SHA}"
      #  org.opencontainers.image.version="${BASE}-${SUB}"
      #  org.opencontainers.image.created="${CI_PIPELINE_STARTED}"
      registry: *dhub
      logins:
        - registry: *dhub
          username:
            from_secret: DOCKER_BKSOL_USER
          password:
            from_secret: DOCKER_BKSOL_PASS