---
#clone:
#  git:
#    image: woodpeckerci/plugin-git
#    settings:
#      depth: 1
#      remote: https://github.com/nextcloud/docker.git

variables:
  - &dhub https://index.docker.io/v1/
  - &arch linux/amd64
  - &repo bksolutions/nextcloud

matrix:
  BASE:
    - apache
  SUB:
    - full
    - cron
    - smb

steps:
  buildx:
    when:
      - branch: main
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: https://github.com/nextcloud/docker.git#master:.examples/dockerfiles/${SUB}/${BASE}/Dockerfile
      platforms: *arch
      dry_run: true
      repo: *repo
      tags: 
        - ${BASE}-${SUB}
      build_args:
        - VERSION="${BASE}-${SUB}"
        - CREATED="${CI_PIPELINE_STARTED}"
        - REVISION="${CI_COMMIT_SHA}"
      #label:
      #  org.opencontainers.image.revision="${CI_COMMIT_SHA}"
      #  org.opencontainers.image.version="${BASE}-${SUB}"
      #  org.opencontainers.image.created="${CI_PIPELINE_STARTED}"
      registry: *dhub
      logins:
        - registry: *dhub
          username:
            from_secret: DOCKER_BKSOL_USER
          password:
            from_secret: DOCKER_BKSOL_PASS