---
variables:
  - &file Dockerfile
  - &dhub https://index.docker.io/v1/
  #- &arch linux/arm/v7,linux/arm64/v8,linux/amd64,linux/i386
  - &arch linux/amd64
  - &repo bksolutions/nextcloud

matrix:
  NC_VERSION:
    - apache
    - 31-apache
    - 30-apache

steps:
  build_n_push:
    when:
      - event: [push]
        branch: main
        path:
          include: ['Dockerfile', '.woodpecker/dockerhub_deploy.yml']
      - event: [cron, manual]
        branch: main
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: *arch
      dry_run: false
      repo: *repo
      tags: 
        - ${NC_VERSION}
      build_args:
        - VERSION=${NC_VERSION}
        - CREATED="${CI_PIPELINE_STARTED}"
        - REVISION="${CI_COMMIT_SHA}"
      registry: *dhub
      logins:
        - registry: *dhub
          username:
            from_secret: DOCKER_BKSOL_USER
          password:
            from_secret: DOCKER_BKSOL_PASS