---
clone:
  - name: git
    image: woodpeckerci/plugin-git
    settings:
      recursive: true
      submodule_override:
        nextcloud: https://github.com/nextcloud/docker.git

when:
  - branch: main
    event: [push]


matrix:
  BASE:
    - apache
    - none

steps:
  pull:
    image: quay.io/skopeo/stable:latest
    commands:
      - skopeo sync --dest-creds $${FORGEJO_CI_USER}:$${FORGEJO_CI_PASS} --src docker --dest docker docker.io/nextcloud:${BASE} forgejo.home309.duckdns.org/containerimages/nextcloud
    #  - skopeo login --username $${FORGEJO_CI_USER} --password $${FORGEJO_CI_PASS} forgejo.home309.duckdns.org/containerimages/nextcloud
    #  - skopeo sync --src docker --dest docker docker.io/nextcloud:${BASE} forgejo.home309.duckdns.org/containerimages/nextcloud
    #  - skopeo logout forgejo.home309.duckdns.org
