---
clone:
  - name: git
    image: woodpeckerci/plugin-git
    settings:
      recursive: true
      submodule_override:
        nextcloud: https://github.com/nextcloud/docker.git

when:
  - branch: main
    event: [push]


matrix:
  BASE:
    - apache

steps:
  login:
    image: quay.io/skopeo/stable:latest
    commands:
      - login -u ${FORGEJO_CI_USER} -p ${FORGEJO_CI_PASS}
  sync:
    image: quay.io/skopeo/stable:latest
    commands:
      - sync \
        --src docker \
        --dest docker \
        docker.io/nextcloud:${BASE} \
        forgejo.home309.duckdns.org/containerimages/nextcloud
