---
clone:
  - name: git
    image: woodpeckerci/plugin-git
    settings:
      recursive: true
      submodule_override:
        nextcloud: https://github.com/nextcloud/docker.git

when:
  - branch: main
    event: [push]


matrix:
  BASE:
    - apache

steps:
  sync:
    image: quay.io/skopeo/stable:latest
    commands:
    #  - skopeo login --username ${FORGEJO_CI_USER} --password ${FORGEJO_CI_PASS} forgejo.home309.duckdns.org/containerimages/nextcloud
      - skopeo sync --dest-registry-token 184a03efd7f838473827557c1d56c70c666cf9be --src docker --dest docker docker.io/nextcloud:${BASE} forgejo.home309.duckdns.org/containerimages/nextcloud
    #  - skopeo logout forgejo.home309.duckdns.org
