---
clone:
  - name: git
    image: woodpeckerci/plugin-git
    settings:
      recursive: true
      submodule_override:
        nextcloud: https://github.com/nextcloud/docker.git

when:
  - branch: main
    event: [push]


matrix:
  BASE:
    - apache

steps:
  sync:
    name: Sync nextcloud image from docker.io to local registry 
    image: quay.io/skopeo/stable:latest
    commands:
      - sync \
        --src docker \
        --dest docker \
        --dest-creds ${FORGEJO_CI_USER}:${FORGEJO_CI_PASS} \
        docker.io/nextcloud:${BASE} \
        forgejo.home309.duckdns.org/containerimages/nextcloud
